name: Scheduled Build

on:
  workflow_dispatch:
  schedule:
    # Runs "at 6am every day" (see https://crontab.guru)
    - cron: '0 6 * * *'
jobs:
  publish:
    name: Scheduled Build
    steps:
      - name: Publish
        uses: ./.github/workflows/publish.yaml
